Document: qpm
Title: Debian qpm Manual
Author: <insert document author here>
Abstract: This manual describes what qpm is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qpm/qpm.sgml.gz

Format: postscript
Files: /usr/share/doc/qpm/qpm.ps.gz

Format: text
Files: /usr/share/doc/qpm/qpm.text.gz

Format: HTML
Index: /usr/share/doc/qpm/html/index.html
Files: /usr/share/doc/qpm/html/*.html
